"""Initial migration with Company model

Revision ID: 3c20b35eadd0
Revises: 
Create Date: 2025-10-04 09:50:47.714208

"""
from typing import Sequence, Union

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3c20b35eadd0'
down_revision: Union[str, Sequence[str], None] = 'bdb238e2d2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cik', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedded_description', Vector(1536), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('sic', sa.String(length=10), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('full_time_employees', sa.Integer(), nullable=True),
    sa.Column('cluster', sa.Integer(), nullable=True),
    sa.Column('umap_x', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('umap_y', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('norm_mcap', sa.Integer(), nullable=True),
    sa.Column('norm_tot_rev', sa.Integer(), nullable=True),
    sa.Column('norm_fte', sa.Integer(), nullable=True),
    sa.Column('louvain_community', sa.Integer(), nullable=True),
    sa.Column('leiden_community', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=True)
    op.create_index(op.f('ix_companies_cluster'), 'companies', ['cluster'], unique=False)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_companies_leiden_community'), 'companies', ['leiden_community'], unique=False)
    op.create_index(op.f('ix_companies_louvain_community'), 'companies', ['louvain_community'], unique=False)
    op.create_index(op.f('ix_companies_sic'), 'companies', ['sic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_sic'), table_name='companies')
    op.drop_index(op.f('ix_companies_louvain_community'), table_name='companies')
    op.drop_index(op.f('ix_companies_leiden_community'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_cluster'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
