"""Add CompanyFacts table

Revision ID: 8dfba2b8c72a
Revises: 3c20b35eadd0
Create Date: 2025-10-04 11:01:20.242449

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8dfba2b8c72a'
down_revision: Union[str, Sequence[str], None] = '3c20b35eadd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cik', sa.Integer(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=10), nullable=False),
    sa.Column('filing_period', sa.String(length=10), nullable=False),
    sa.Column('form_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_facts_cik'), 'company_facts', ['cik'], unique=False)
    op.create_index(op.f('ix_company_facts_fact'), 'company_facts', ['fact'], unique=False)
    op.create_index(op.f('ix_company_facts_filing_period'), 'company_facts', ['filing_period'], unique=False)
    op.create_index(op.f('ix_company_facts_fiscal_year'), 'company_facts', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_company_facts_form_type'), 'company_facts', ['form_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_facts_form_type'), table_name='company_facts')
    op.drop_index(op.f('ix_company_facts_fiscal_year'), table_name='company_facts')
    op.drop_index(op.f('ix_company_facts_filing_period'), table_name='company_facts')
    op.drop_index(op.f('ix_company_facts_fact'), table_name='company_facts')
    op.drop_index(op.f('ix_company_facts_cik'), table_name='company_facts')
    op.drop_table('company_facts')
    # ### end Alembic commands ###
