"""Add CompanyFacts table with constraints

Revision ID: b03486763d66
Revises: 8dfba2b8c72a
Create Date: 2025-10-04 11:52:28.198719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03486763d66'
down_revision: Union[str, Sequence[str], None] = '8dfba2b8c72a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_facts', 'value',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_facts', 'value',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
